# Generated by Django 3.2.3 on 2021-05-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
