# Generated by Django 3.2.3 on 2021-06-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxway', '0003_auto_20210601_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
