# Generated by Django 3.2.3 on 2021-06-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxway', '0004_auto_20210601_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
