# Generated by Django 3.2.3 on 2021-06-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxway', '0005_rename_product_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
    ]
