# Generated by Django 3.2.3 on 2021-06-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxway', '0006_rename_products_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
