# Generated by Django 3.2.3 on 2021-06-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxway', '0007_auto_20210602_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
